version: "3.4"
services:
  webserver:
    image: nginx:1.12.2-alpine
    restart: on-failure
    volumes:
      - type: bind
        source: ./dist
        target: /usr/share/nginx/html
    ports:
      - 80:80