version: "3.4"
services:
  nuxt:
    image: cybercangaco/client.environment:stable
    build: .docker
    volumes:
      - type: bind
        source: ./
        target: /usr/share/src
    ports:
      - 3000:3000
      # - 9229:9229 # node debug
    command: dev